// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'bridge_models.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CLIENT_STATE`, `TOKIO_RUNTIME`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

Future<String> createRoom({
  required String serverAddr,
  required String username,
}) => RustLib.instance.api.crateApiCreateRoom(
  serverAddr: serverAddr,
  username: username,
);

Future<List<FlutterPathFull>> joinRoom({
  required String serverAddr,
  required String username,
  required String roomId,
}) => RustLib.instance.api.crateApiJoinRoom(
  serverAddr: serverAddr,
  username: username,
  roomId: roomId,
);

Stream<EventMessage> listenEvents() =>
    RustLib.instance.api.crateApiListenEvents();

Stream<EventMessage> replayRoom({
  required String serverAddr,
  required String logFilename,
}) => RustLib.instance.api.crateApiReplayRoom(
  serverAddr: serverAddr,
  logFilename: logFilename,
);

BigInt startPath({
  required FlutterPoint point,
  required int color,
  required double strokeWidth,
}) => RustLib.instance.api.crateApiStartPath(
  point: point,
  color: color,
  strokeWidth: strokeWidth,
);

Future<void> appendToPath({
  required BigInt pathId,
  required FlutterPoint point,
}) => RustLib.instance.api.crateApiAppendToPath(pathId: pathId, point: point);

Future<void> endPath({required BigInt pathId}) =>
    RustLib.instance.api.crateApiEndPath(pathId: pathId);

Future<void> sendAudioChunk({
  required List<int> data,
  required PlatformInt64 sequence,
}) =>
    RustLib.instance.api.crateApiSendAudioChunk(data: data, sequence: sequence);

Future<void> disconnect() => RustLib.instance.api.crateApiDisconnect();
