// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EventMessage {
  final Uint8List data;

  const EventMessage({required this.data});

  @override
  int get hashCode => data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventMessage &&
          runtimeType == other.runtimeType &&
          data == other.data;
}

class FlutterPathFull {
  final BigInt pathId;
  final List<FlutterPoint> points;
  final int color;
  final double strokeWidth;

  const FlutterPathFull({
    required this.pathId,
    required this.points,
    required this.color,
    required this.strokeWidth,
  });

  @override
  int get hashCode =>
      pathId.hashCode ^ points.hashCode ^ color.hashCode ^ strokeWidth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPathFull &&
          runtimeType == other.runtimeType &&
          pathId == other.pathId &&
          points == other.points &&
          color == other.color &&
          strokeWidth == other.strokeWidth;
}

class FlutterPoint {
  final double dx;
  final double dy;

  const FlutterPoint({required this.dx, required this.dy});

  @override
  int get hashCode => dx.hashCode ^ dy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPoint &&
          runtimeType == other.runtimeType &&
          dx == other.dx &&
          dy == other.dy;
}
